saas_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      user: "{{ env_var('POSTGRES_USER', 'analytics_user') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'analytics_pass') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'saas_analytics') }}"
      schema: public
      threads: 4
